/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Dofus Pulse API
 * API documentation
 * OpenAPI spec version: 1.0
 */

export interface CreateGearSetRequest {
  /** @minLength 1 */
  title?: string;
  /** @minLength 1 */
  characterClass?: string;
  /**
   * @minLength 1
   * @pattern ^[mf]$
   */
  characterGender?: string;
  /**
   * @minItems 0
   * @maxItems 10
   */
  tags?: string[];
}
