/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Dofus Pulse API
 * API documentation
 * OpenAPI spec version: 1.0
 */

export interface DailySales {
  date?: string;
  sold?: number;
  added?: number;
  expired?: number;
  avgSoldDuration?: number;
  listingCount?: number;
  revenue?: number;
}
