/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Dofus Pulse API
 * API documentation
 * OpenAPI spec version: 1.0
 */
import type { CharacterClassDto } from "./characterClassDto";
import type { GearSetSlotDto } from "./gearSetSlotDto";

export interface GearSetDto {
	id?: number;
	title?: string;
	characterClass?: CharacterClassDto;
	characterGender?: string;
	tags?: string[];
	slots?: GearSetSlotDto[];
}
