/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Dofus Pulse API
 * API documentation
 * OpenAPI spec version: 1.0
 */

import type {GearSetSlotTypeDto} from "./gearSetSlotTypeDto";
import type {ItemDetailsDto} from "./itemDetailsDto";

export interface GearSetSlotDto {
  id?: number;
  itemDetails?: ItemDetailsDto;
  slotType?: GearSetSlotTypeDto;
}
