/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Dofus Pulse API
 * API documentation
 * OpenAPI spec version: 1.0
 */
import type { Pageable } from "./pageable";

export type GetAllItemTypesParams = {
	pageable: Pageable;
};
