/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Dofus Pulse API
 * API documentation
 * OpenAPI spec version: 1.0
 */

export type GetItemPerformanceMetricsParams = {
	startDate: string;
	endDate: string;
};
