/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Dofus Pulse API
 * API documentation
 * OpenAPI spec version: 1.0
 */

export * from "./characterClassDto";
export * from "./createGearSetRequest";
export * from "./dailySales";
export * from "./dailySalesList";
export * from "./effectDto";
export * from "./equipItemRequest";
export * from "./gearSetDto";
export * from "./gearSetSlotDto";
export * from "./gearSetSlotTypeDto";
export * from "./getAllItemDetailsParams";
export * from "./getAllItemTypesParams";
export * from "./getItemPerformanceMetricsParams";
export * from "./getItemPriceHistoryParams";
export * from "./getItemProfitMetricsHistoryParams";
export * from "./getItemSalesHistoryParams";
export * from "./getItemsDailySalesHistoryParams";
export * from "./getItemsPerformanceMetricsParams";
export * from "./getItemsProfitMetricsHistoryParams";
export * from "./itemDetailsDto";
export * from "./itemDetailsSearchCriteria";
export * from "./itemEffectDto";
export * from "./itemPerformance";
export * from "./itemPrice";
export * from "./itemTypeDto";
export * from "./loginRequest";
export * from "./pageable";
export * from "./pagedModelItemDetailsDto";
export * from "./pagedModelItemTypeDto";
export * from "./pageMetadata";
export * from "./problemDetail";
export * from "./problemDetailProperties";
export * from "./profitMetrics";
export * from "./profitMetricsList";
export * from "./registerRequest";
export * from "./userProfileDto";
export * from "./userProfileDtoAttributes";
export * from "./userProfileDtoRole";
export * from "./userSocialLoginDto";
