/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Dofus Pulse API
 * API documentation
 * OpenAPI spec version: 1.0
 */
import type {ItemEffectDto} from "./itemEffectDto";

export interface ItemDetailsDto {
  id?: number;
  name?: string;
  level?: number;
  itemTypeId?: number;
  iconId?: number;
  ingredientIds?: number[];
  possibleEffects?: ItemEffectDto[];
}
