/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Dofus Pulse API
 * API documentation
 * OpenAPI spec version: 1.0
 */

export interface ItemPerformance {
	itemId?: number;
	salesVolume?: number;
	salesVelocity?: number;
	avgCraftCost?: number;
	avgListingPrice?: number;
	avgDailyProfitMargin?: number;
	profitMarginTrend?: number;
	craftCostTrend?: number;
	priceTrend?: number;
	salesTrend?: number;
	listingsTrend?: number;
	roiTrend?: number;
	avgSoldDuration?: number;
	craftCostPctChangeFromAvg?: number;
}
