/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Dofus Pulse API
 * API documentation
 * OpenAPI spec version: 1.0
 */

export interface ItemDetailsSearchCriteria {
	/**
	 * @minLength 0
	 * @maxLength 100
	 */
	name?: string;
	types?: number[];
	typesNames?: string[];
	effect?: number;
	ingredient?: number;
	/**
	 * @minimum 1
	 * @maximum 200
	 */
	minLevel?: number;
	/**
	 * @minimum 1
	 * @maximum 200
	 */
	maxLevel?: number;
}
