/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Dofus Pulse API
 * API documentation
 * OpenAPI spec version: 1.0
 */
import type { ItemDetailsDto } from "./itemDetailsDto";
import type { PageMetadata } from "./pageMetadata";

export interface PagedModelItemDetailsDto {
	content?: ItemDetailsDto[];
	page?: PageMetadata;
}
