/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Dofus Pulse API
 * API documentation
 * OpenAPI spec version: 1.0
 */
import type {ItemTypeDto} from "./itemTypeDto";
import type {PageMetadata} from "./pageMetadata";

export interface PagedModelItemTypeDto {
  content?: ItemTypeDto[];
  page?: PageMetadata;
}
