/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Dofus Pulse API
 * API documentation
 * OpenAPI spec version: 1.0
 */

export interface Pageable {
	/** @minimum 0 */
	page?: number;
	/** @minimum 1 */
	size?: number;
	sort?: string[];
}
