/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Dofus Pulse API
 * API documentation
 * OpenAPI spec version: 1.0
 */

export interface RegisterRequest {
	/** @minLength 1 */
	email?: string;
	password?: string[];
}
