/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Dofus Pulse API
 * API documentation
 * OpenAPI spec version: 1.0
 */

import type {UserProfileDtoAttributes} from "./userProfileDtoAttributes";
import type {UserProfileDtoRole} from "./userProfileDtoRole";
import type {UserSocialLoginDto} from "./userSocialLoginDto";

export interface UserProfileDto {
  id?: number;
  email?: string;
  role?: UserProfileDtoRole;
  socials?: UserSocialLoginDto[];
  attributes?: UserProfileDtoAttributes;
  createdAt?: string;
  updatedAt?: string;
}
