/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Dofus Pulse API
 * API documentation
 * OpenAPI spec version: 1.0
 */

export type UserProfileDtoRole =
    (typeof UserProfileDtoRole)[keyof typeof UserProfileDtoRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserProfileDtoRole = {
  ADMIN: "ADMIN",
  USER: "USER",
} as const;
