import {initContract} from "@ts-rest/core";
import {z} from "zod";

import {
  CreateGearsetSchema,
  createPaginatedSchema,
  DailySalesListSchema,
  DailySalesSchema,
  DateRangeSchema,
  EffectSchema,
  EquipItemRequestSchema,
  GearSetSchema,
  GearSetSlotSchema,
  GearSetSlotTypeSchema,
  IdPathParam,
  ItemDetailsParamsSchema,
  ItemDetailsSchema,
  ItemMetricsParamsSchema,
  ItemPerformanceSchema,
  ItemPriceSchema,
  ItemsProfitMetricsSchema,
  ItemTypeSchema,
  LoginRequestSchema,
  PageableParamsSchema,
  ProblemDetailSchema,
  ProfitMetricsEntrySchema,
  RegisterRequestSchema,
  UpdateGearsetSchema,
  UserSchema,
} from "@/services/api/api.types";

const c = initContract();

export const contract = c.router({
  getUser: {
    path: "/api/v1/user/me",
    method: "GET",
    responses: {
      200: UserSchema,
      401: ProblemDetailSchema,
    },
    summary: "Get current user info",
  },
  loginUser: {
    path: "/api/v1/auth/login",
    method: "POST",
    body: LoginRequestSchema,
    responses: {
      200: UserSchema,
      400: ProblemDetailSchema,
      403: ProblemDetailSchema,
    },
  },
  registerUser: {
    path: "/api/v1/auth/register",
    method: "POST",
    body: RegisterRequestSchema,
    responses: {
      200: UserSchema,
      400: ProblemDetailSchema,
      403: ProblemDetailSchema,
      409: ProblemDetailSchema,
    },
  },
  getItemTypes: {
    path: "/api/v1/item-types",
    method: "GET",
    query: PageableParamsSchema,
    responses: {
      200: createPaginatedSchema(ItemTypeSchema),
      400: ProblemDetailSchema,
      401: ProblemDetailSchema,
      404: ProblemDetailSchema,
    },
    summary: "Get item types",
  },
  getItemTypeById: {
    path: "/api/v1/item-types/:id",
    method: "GET",
    pathParams: IdPathParam,
    responses: {
      200: ItemTypeSchema,
      400: ProblemDetailSchema,
      401: ProblemDetailSchema,
      404: ProblemDetailSchema,
    },
    summary: "Get item type by id",
  },
  getItems: {
    path: "/api/v1/items",
    method: "GET",
    query: ItemDetailsParamsSchema,
    responses: {
      200: createPaginatedSchema(ItemDetailsSchema),
      400: ProblemDetailSchema,
      401: ProblemDetailSchema,
    },
    summary: "Get a paginated and filtered list of items",
  },
  getItemById: {
    path: "/api/v1/items/:id",
    method: "GET",
    pathParams: IdPathParam,
    responses: {
      200: ItemDetailsSchema,
      400: ProblemDetailSchema,
      401: ProblemDetailSchema,
      404: ProblemDetailSchema,
    },
    summary: "Get an item by id",
  },
  getEffectById: {
    path: "/api/v1/effects/:id",
    method: "GET",
    pathParams: IdPathParam,
    responses: {
      200: EffectSchema,
      400: ProblemDetailSchema,
      401: ProblemDetailSchema,
      404: ProblemDetailSchema,
    },
    summary: "Get an effect by id",
  },
  getEffects: {
    path: "/api/v1/effects",
    method: "GET",
    responses: {
      200: z.array(EffectSchema),
      401: ProblemDetailSchema,
    },
    summary: "Get all effects",
  },
  getUserGearsets: {
    path: "/api/v1/user/gearsets",
    method: "GET",
    responses: {
      200: z.array(GearSetSchema),
      401: ProblemDetailSchema,
    },
    summary: "Get current user gearsets",
  },
  getGearsetById: {
    path: "/api/v1/gearsets/:id",
    pathParams: IdPathParam,
    method: "GET",
    responses: {
      200: GearSetSchema,
      400: ProblemDetailSchema,
      401: ProblemDetailSchema,
      403: ProblemDetailSchema,
      404: ProblemDetailSchema,
    },
    summary: "Get gearset by id",
  },
  createGearset: {
    path: "/api/v1/gearsets",
    method: "POST",
    body: CreateGearsetSchema,
    responses: {
      201: GearSetSchema,
      400: ProblemDetailSchema,
      404: ProblemDetailSchema,
    },
    summary: "Create a new gearset",
  },
  updateGearset: {
    path: "/api/v1/gearsets/:id",
    method: "PUT",
    body: UpdateGearsetSchema,
    pathParams: IdPathParam,
    responses: {
      200: GearSetSchema,
      400: ProblemDetailSchema,
      401: ProblemDetailSchema,
      404: ProblemDetailSchema,
    },
    summary: "Update a gearset",
  },
  deleteGearsetById: {
    path: "/api/v1/gearsets/:id",
    method: "DELETE",
    pathParams: IdPathParam,
    responses: {
      204: c.type<void>(),
      400: ProblemDetailSchema,
      401: ProblemDetailSchema,
      404: ProblemDetailSchema,
    },
    summary: "Delete a gearset by id",
  },
  getGearsetSlotTypes: {
    path: "/api/v1/gearset-slot-types",
    method: "GET",
    responses: {
      200: z.array(GearSetSlotTypeSchema),
      401: ProblemDetailSchema,
    },
    summary: "Get gearset slot types",
  },
  equipItem: {
    path: "/api/v1/gearsets/:gearSetId/slots",
    method: "POST",
    body: EquipItemRequestSchema,
    pathParams: z.object({gearSetId: z.number()}),
    responses: {
      200: GearSetSlotSchema,
      400: ProblemDetailSchema,
      401: ProblemDetailSchema,
      403: ProblemDetailSchema,
      404: ProblemDetailSchema,
    },
    summary: "Equip an item in a gearset",
  },
  unequipItem: {
    path: "/api/v1/gearsets/:gearSetId/slots/:slotId",
    method: "DELETE",
    pathParams: z.object({
      gearSetId: z.number(),
      slotId: z.number(),
    }),
    responses: {
      204: c.type<void>(),
      400: ProblemDetailSchema,
      401: ProblemDetailSchema,
      403: ProblemDetailSchema,
      404: ProblemDetailSchema,
    },
    summary: "Unequip an item in a gearset",
  },
  getItemSalesHistory: {
    path: "/api/v1/items/:id/sales-history",
    method: "GET",
    pathParams: IdPathParam,
    query: DateRangeSchema,
    responses: {
      200: z.array(DailySalesSchema),
      400: ProblemDetailSchema,
      401: ProblemDetailSchema,
      404: ProblemDetailSchema,
    },
    summary: "Get sales history for an item",
  },
  getItemProfitMetricsHistory: {
    path: "/api/v1/items/:id/profit-metrics",
    method: "GET",
    pathParams: IdPathParam,
    query: DateRangeSchema,
    responses: {
      200: z.array(ProfitMetricsEntrySchema),
      400: ProblemDetailSchema,
      401: ProblemDetailSchema,
      404: ProblemDetailSchema,
    },
    summary: "Get profit metrics history for an item",
  },
  getItemPriceHistory: {
    path: "/api/v1/items/:id/price-history",
    method: "GET",
    pathParams: IdPathParam,
    query: DateRangeSchema,
    responses: {
      200: z.array(ItemPriceSchema),
      400: ProblemDetailSchema,
      401: ProblemDetailSchema,
      404: ProblemDetailSchema,
    },
    summary: "Get price history for an item",
  },
  getItemPerformance: {
    path: "/api/v1/items/:id/performance",
    method: "GET",
    pathParams: IdPathParam,
    query: DateRangeSchema,
    responses: {
      200: ItemPerformanceSchema,
      400: ProblemDetailSchema,
      401: ProblemDetailSchema,
      404: ProblemDetailSchema,
    },
    summary: "Get performance metrics for an item",
  },
  getItemsDailySalesHistory: {
    path: "/api/v1/items/sales-history",
    method: "GET",
    query: ItemMetricsParamsSchema,
    responses: {
      200: z.array(DailySalesListSchema),
      400: ProblemDetailSchema,
      401: ProblemDetailSchema,
    },
    summary: "Get sales history for multiple items",
  },
  getItemsProfitMetricsHistory: {
    path: "/api/v1/items/profit-metrics",
    method: "GET",
    query: ItemMetricsParamsSchema,
    responses: {
      200: ItemsProfitMetricsSchema,
      400: ProblemDetailSchema,
      401: ProblemDetailSchema,
    },
    summary: "Get profit metrics for multiple items",
  },
  getItemsPerformanceMetrics: {
    path: "/api/v1/items/performance",
    method: "GET",
    query: ItemMetricsParamsSchema,
    responses: {
      200: z.array(ItemPerformanceSchema),
      400: ProblemDetailSchema,
      401: ProblemDetailSchema,
    },
    summary: "Get performance metrics for multiple items",
  },
});
